### ISSUE TITLE
plt.gca doesn't take arguments on matplotlib 3.6

### ISSUE THREAD

**Issue by meono** [hirsch-lab/spiderplot#1]
I got this error going through the first example:

`TypeError: gca() got an unexpected keyword argument 'polar'`

It looks like gca doesn't take arguments with matplotlib 3.6.

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.gca.html

version 3.5.3 works fine for me.

**Comment by normanius** [comment]
Thanks for reporting this. 

The problem should be fixed in the newest release of the package.

```bash
pip install spiderplot --upgrade
```
